timeline
    title The History of the Internet (1969 - 2005)
    1960s : ARPANET sends its first message from one network to another.
          : The ARPANET network is established.
    1970s : Ray Tomlinson develops the standard email address format.
          : ARPANET makes its first trans-Atlantic connection.
          : TCP and IP are introduced.
          : Dennis Hayes and Dale Heatherington develop the first PC modem.
          : Gary Thuerk sends the first spam message.
    1980s : The Domain Name System (DNS) is created.
          : John Postel introduces the first top-level domains (.com, .org, .gov, .edu, .mil).
          : AOL is launched.
    1990s : Tim Berners-Lee's World Wide Web goes live.
          : The first web browser, Mosaic, is invented.
          : The first search engine, WebCrawler, goes live.
          : Netscape allows millions to easily navigate the internet.
          : Amazon and eBay (AuctionWeb) go live.
          : Hotmail becomes the first free, web-based email provider.
          : The world is introduced to wireless internet (Wi-Fi).
    2000s : Wikipedia goes live.
          : Facebook goes live.
          : YouTube goes live.
